#!/bin/bash


MODE_DEBUG=no

### debuge MESSAGE Usage:
# print a blue debug message to stderr
# only prints if MODE_DEBUG is set to "yes"
###/doc
function debuge {
	if [[ "$MODE_DEBUG" = yes ]]; then
		echo -e "${CBBLU}DEBUG:$CBLU$@$CDEF" 1>&2
	fi
}

### infoe MESSAGE Usage:
# print a green informational message to stdout
###/doc
function infoe {
	echo -e "$CGRN$@$CDEF"
}

### warne MESSAGE Usage:
# print a yellow warning message to stderr
###/doc
function warne {
	echo -e "${CBYEL}WARN:$CYEL $@$CDEF" 1>&2
}

### faile MESSAGE CODE Usage:
# print a red failure message to stderr and exit with CODE
# CODE must be a number
# if no code is specified, error code 127 is used
###/doc
function faile {
	local MSG=
	local ARG=
	local ERCODE=127
	local numpat='^[0-9]+$'
	while [[ -n "$@" ]]; do
		ARG=$1 ; shift
		if [[ -z "$@" ]] && [[ "$ARG" =~ $numpat ]]; then
			ERCODE=$ARG
		else
			MSG="$MSG $ARG"
		fi
	done
	echo "${CBRED}ERROR FAIL:$CRED$MSG$CDEF" 1>&2
	exit "$ERCODE"
}


function mustberoot {
	if [[ "$UID" != 0 ]]; then
		faile "You must be root"
	fi
}

function uconfirm {
	read -p "%@ [y/N]"
	local ans='^yes|YES|y|Y$'
	[[ "$REPLY" =~ $ans ]]
}

set -u

mustberoot

### Install Minetest Usage:help
# Installs the latest minetest from PPA, all modules, plus some neat extras like Carbone NG,
# 3d-armor mod, creatures mod and others.
###/doc

ppafile="/etc/apt/sources.list.d/minetestppa.list"
distro=$(cat /etc/lsb-release | grep DISTRIB_CODENAME | cut -d'=' -f2)

echo "deb http://ppa.launchpad.net/minetestdevs/stable/ubuntu $distro main" >> "$ppafile"
echo "deb-src http://ppa.launchpad.net/minetestdevs/stable/ubuntu $distro main" >> "$ppafile"

apt update

apt install minetest* git

minedir="$HOME/.minetest"
mkdir -p "$minedir/"{games,mods,downloads}
cd "$minedir/games"
git clone "https://github.com/Calinou/carbone-ng"

cd ../downloads
git clone "https://github.com/stujones11/minetest-3d_armor"
mv minetest-3d_armor/3d_armor ../mods/

cd ../mods
git clone "https://github.com/BlockMen/cme"
git clone "https://github.com/minetest-technic/unified_inventory/"

uconfirm "Install NSSM? (difficult monsters, large download ~120 MB)" && git clone "https://github.com/NPXcoot/nssm"

# ==================================

cat <<EOF

Minetest has been successfully installed

You can run minetest from your applications menu; or simply type the command "minetest"

You have the main minetest-game and carbone-ng games

To get started:

1. Select the minetest or Carbone game (the menu area will change to reflect the selected game)
2. Create a new world - call it what you want, use a few random characters as the seed
3. go to the Server tab and select your world, click Configure
4. Select mods to enable or disable on the right
	* cme : create creatures you can farm and fight
	* 3d_armor : allows you to create and equip armor
	* unified_inventory : gives you access to all loaded mods and blocks (only recommended for creative mode)
	* If you chose to install NSSM, you have th option to enable difficult monsters
5. Click save, return to the Singleplayer tab
6. Start playing!

Getting more mods and subgames:

See http://www.minetest.net/customize/

This script will eventually be updated to also make adding subgames and mods easier.

EOF
